function snippet(data, rootUrl) {
	let newData = data
	data.links.map( (link, index) => {
		return (
			newData.links[index] = newData.selectedSite + link
		)
	});

return `<table align="center" width="100%" border="0" cellpadding="0" cellspacing="0">\n <tr>\n  <td align="center" width="33.3%" style="padding-top: 20px; padding-bottom:20px; font-family: CenturyGothic, Futura, Verdana, sans-serif; font-size: 20px; color: #000000; letter-spacing: .15em; line-height: 200%;">\n   <a _label="product-grid" href="${newData.links[0]}">\n    <img width="194" src="${newData.images[0]}" style="display:block; border-style: none;">\n   </a>\n  </td>\n  <td align="center" width="33.3%" style="padding-top: 20px; padding-bottom:20px; font-family: CenturyGothic, Futura, Verdana, sans-serif; font-size: 20px; color: #000000; letter-spacing: .15em; line-height: 200%;">\n   <a _label="product-grid" href="${newData.links[1]}">\n    <img width="194" src="${newData.images[1]}" style="display:block; border-style: none;">\n   </a>\n  </td>\n  <td align="center" width="33.3%" style="padding-top: 20px; padding-bottom:20px; font-family: CenturyGothic, Futura, Verdana, sans-serif; font-size: 20px; color: #000000; letter-spacing: .15em; line-height: 200%;">\n   <a _label="product-grid" href="${newData.links[2]}">\n    <img width="194" src="${newData.images[2]}" style="display:block; border-style: none;">\n   </a>\n  </td>\n </tr>\n <tr>\n  <td align="center" width="33.3%" style="padding-top: 20px; padding-bottom:20px; font-family: CenturyGothic, Futura, Verdana, sans-serif; font-size: 20px; color: #000000; letter-spacing: .15em; line-height: 200%;">\n   <a _label="product-grid" href="${newData.links[3]}">\n    <img width="194" src="${newData.images[3]}" style="display:block; border-style: none;">\n   </a>\n  </td>\n  <td align="center" width="33.3%" style="padding-top: 20px; padding-bottom:20px; font-family: CenturyGothic, Futura, Verdana, sans-serif; font-size: 20px; color: #000000; letter-spacing: .15em; line-height: 200%;">\n   <a _label="product-grid" href="${newData.links[4]}">\n    <img width="194" src="${newData.images[4]}" style="display:block; border-style: none;">\n   </a>\n  </td>\n  <td align="center" width="33.3%" style="padding-top: 20px; padding-bottom:20px; font-family: CenturyGothic, Futura, Verdana, sans-serif; font-size: 20px; color: #000000; letter-spacing: .15em; line-height: 200%;">\n   <a _label="product-grid" href="${newData.links[5]}">\n    <img width="194" src="${newData.images[5]}" style="display:block; border-style: none;">\n   </a>\n  </td>\n </tr>\n</table>`;
}

export default snippet;