export default function() {
  return [
    {
      name: "GUESS",
      countries: [
        {
          US: [
            {
              Men: [
                {
                  "View All":
                    "https://shop.guess.com/en/catalog/browse/men/view-all/"
                },
                {
                  "New Arrivals":
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/men/view-all/"
                },
                {
                  "Denim":
                    "https://shop.guess.com/en/catalog/browse/denim/men/view-all/"
                },
                {
                  "Tanks & T-shirts":
                    "https://shop.guess.com/en/catalog/browse/men/tanks-t-shirts/view-all/"
                },
                {
                  "Jackets":
                    "https://shop.guess.com/en/catalog/browse/men/jackets-outerwear/view-all/"
                },
                {
                  "Shirts":
                    "https://shop.guess.com/en/catalog/browse/men/shirts/view-all/"
                },
                {
                  "Sweaters":
                    "https://shop.guess.com/en/catalog/browse/men/sweaters/"
                },
                {
                  "Pants & Shorts":
                    "https://shop.guess.com/en/catalog/browse/men/pants-shorts/view-all/"
                },
                {
                  "Activewear":
                    "https://shop.guess.com/en/catalog/browse/men/activewear/"
                },
                {
                  "Underwear":
                    "https://shop.guess.com/en/catalog/browse/men/underwear/"
                },
                {
									"Swim": "https://shop.guess.com/en/catalog/browse/men/swim/"
								}
              ]
            },
            {
              Women: [
                {
                  "View All":
                    "https://shop.guess.com/en/catalog/browse/women/view-all/"
                },
                {
                  "New Arrivals":
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/women/view-all/"
                },
                {
                  "Dresses":
                    "https://shop.guess.com/en/catalog/browse/women/dresses/view-all/"
                },
                {
                  "Denim":
                    "https://shop.guess.com/en/catalog/browse/denim/women/view-all/"
                },
                {
                  "Tops":
                    "https://shop.guess.com/en/catalog/browse/women/tops/view-all/"
                },
                {
                  "Jackets":
                    "https://shop.guess.com/en/catalog/browse/women/jackets-and-outerwear/view-all/"
                },
                {
                  "Sweaters":
                    "https://shop.guess.com/en/catalog/browse/women/sweaters/"
                },
                {
                  "Bottoms":
                    "https://shop.guess.com/en/catalog/browse/women/bottoms/view-all/"
                },
                {
                  "Activewear":
                    "https://shop.guess.com/en/catalog/browse/women/activewear/"
                },
                {
                  "Swim":
                    "https://shop.guess.com/en/catalog/browse/women/swimwear/view-all/"
                },
                {
                  "Lingerie":
                    "https://shop.guess.com/en/catalog/browse/women/lingerie/view-all/"
                }
              ]
            }
          ]
        },
        {
          CA: [
            {
              Men: [
                {
                  "View All":
                    "https://www.guess.ca/en/catalog/browse/men/view-all/"
                },
                {
                  "New Arrivals":
                    "https://www.guess.ca/en/catalog/browse/new-arrivals/men/view-all/"
                },
                {
                  "Denim":
                    "https://www.guess.ca/en/catalog/browse/denim/men/view-all/"
                },
                {
                  "Tank & T-shirt":
                    "https://www.guess.ca/en/catalog/browse/men/tanks-t-shirts/view-all/"
                },
                {
                  "Jackets":
                    "https://www.guess.ca/en/catalog/browse/men/jackets-outerwear/view-all/"
                },
                {
                  "Shirts":
                    "https://www.guess.ca/en/catalog/browse/men/shirts/view-all/"
                },
                {
                  "Sweaters":
                    "https://www.guess.ca/en/catalog/browse/men/sweaters/"
                },
                {
                  "Pants & Shorts":
                    "https://www.guess.ca/en/catalog/browse/men/pants-shorts/view-all/"
                },
                {
                  "Activewear":
                    "https://www.guess.ca/en/catalog/browse/men/activewear/"
                },
                {
                  "Underwear":
                    "https://www.guess.ca/en/catalog/browse/men/underwear/"
                },
                {
									"Sale": "https://www.guess.ca/en/catalog/browse/sale/men/view-all/"
								}
              ]
            },
            {
              Women: [
                {
                  "View All":
                    "https://www.guess.ca/en/catalog/browse/women/view-all/"
                },
                {
                  "New Arrivals":
                    "https://www.guess.ca/en/catalog/browse/new-arrivals/women/view-all/"
                },
                {
                  "Dresses":
                    "https://www.guess.ca/en/catalog/browse/women/dresses/view-all/"
                },
                {
                  "Tops":
                    "https://www.guess.ca/en/catalog/browse/women/tops/view-all/"
                },
                {
                  "Denim":
                    "https://www.guess.ca/en/Catalog/Browse/denim/women/view-all/"
                },
                {
                  "Jackets":
                    "https://www.guess.ca/en/catalog/browse/women/jackets-and-outerwear/view-all/"
                },
                {
                  "Sweaters":
                    "https://www.guess.ca/en/catalog/browse/women/sweaters/"
                },
                {
                  "Bottoms":
                    "https://www.guess.ca/en/catalog/browse/women/bottoms/view-all/"
                },
                {
                  "Activewear":
                    "https://www.guess.ca/en/catalog/browse/women/activewear/"
                },
                {
                  "Swimwear":
                    "https://www.guess.ca/en/catalog/browse/women/swimwear/view-all/"
                },
                {
									"Lingerie": "https://www.guess.ca/en/catalog/browse/women/lingerie/view-all/"
								}
              ]
            }
          ]
        }
      ]
    },
    {
      name: "GUESS Factory",
      countries: [
        {
          us: [
            {
              men: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/men/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/men/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/men/view-all/"
                },
                {
                  tankAndTshirt:
                    "https://shop.guess.com/en/catalog/browse/men/tanks-t-shirts/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/men/jackets-outerwear/view-all/"
                },
                {
                  shirts:
                    "https://shop.guess.com/en/catalog/browse/men/shirts/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/men/sweaters/"
                },
                {
                  pantsAndShorts:
                    "https://shop.guess.com/en/catalog/browse/men/pants-shorts/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/men/activewear/"
                },
                {
                  underwear:
                    "https://shop.guess.com/en/catalog/browse/men/underwear/"
                },
                { swim: "https://shop.guess.com/en/catalog/browse/men/swim/" }
              ]
            },
            {
              women: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/women/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/women/view-all/"
                },
                {
                  dresses:
                    "https://shop.guess.com/en/catalog/browse/women/dresses/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/women/view-all/"
                },
                {
                  tops:
                    "https://shop.guess.com/en/catalog/browse/women/tops/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/women/jackets-and-outerwear/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/women/sweaters/"
                },
                {
                  bottoms:
                    "https://shop.guess.com/en/catalog/browse/women/bottoms/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/women/activewear/"
                },
                {
                  swim:
                    "https://shop.guess.com/en/catalog/browse/women/swimwear/view-all/"
                },
                {
                  lingerie:
                    "https://shop.guess.com/en/catalog/browse/women/lingerie/view-all/"
                }
              ]
            }
          ]
        },
        {
          ca: [
            {
              men: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/men/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/men/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/men/view-all/"
                },
                {
                  tankAndTshirt:
                    "https://shop.guess.com/en/catalog/browse/men/tanks-t-shirts/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/men/jackets-outerwear/view-all/"
                },
                {
                  shirts:
                    "https://shop.guess.com/en/catalog/browse/men/shirts/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/men/sweaters/"
                },
                {
                  pantsAndShorts:
                    "https://shop.guess.com/en/catalog/browse/men/pants-shorts/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/men/activewear/"
                },
                {
                  underwear:
                    "https://shop.guess.com/en/catalog/browse/men/underwear/"
                },
                { swim: "https://shop.guess.com/en/catalog/browse/men/swim/" }
              ]
            },
            {
              women: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/men/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/men/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/men/view-all/"
                },
                {
                  tankAndTshirt:
                    "https://shop.guess.com/en/catalog/browse/men/tanks-t-shirts/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/men/jackets-outerwear/view-all/"
                },
                {
                  shirts:
                    "https://shop.guess.com/en/catalog/browse/men/shirts/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/men/sweaters/"
                },
                {
                  pantsAndShorts:
                    "https://shop.guess.com/en/catalog/browse/men/pants-shorts/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/men/activewear/"
                },
                {
                  underwear:
                    "https://shop.guess.com/en/catalog/browse/men/underwear/"
                },
                { swim: "https://shop.guess.com/en/catalog/browse/men/swim/" }
              ]
            }
          ]
        }
      ]
    },
    {
      name: "G by GUESS",
      countries: [
        {
          us: [
            {
              men: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/men/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/men/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/men/view-all/"
                },
                {
                  tankAndTshirt:
                    "https://shop.guess.com/en/catalog/browse/men/tanks-t-shirts/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/men/jackets-outerwear/view-all/"
                },
                {
                  shirts:
                    "https://shop.guess.com/en/catalog/browse/men/shirts/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/men/sweaters/"
                },
                {
                  pantsAndShorts:
                    "https://shop.guess.com/en/catalog/browse/men/pants-shorts/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/men/activewear/"
                },
                {
                  underwear:
                    "https://shop.guess.com/en/catalog/browse/men/underwear/"
                },
                { swim: "https://shop.guess.com/en/catalog/browse/men/swim/" }
              ]
            },
            {
              women: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/women/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/women/view-all/"
                },
                {
                  dresses:
                    "https://shop.guess.com/en/catalog/browse/women/dresses/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/women/view-all/"
                },
                {
                  tops:
                    "https://shop.guess.com/en/catalog/browse/women/tops/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/women/jackets-and-outerwear/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/women/sweaters/"
                },
                {
                  bottoms:
                    "https://shop.guess.com/en/catalog/browse/women/bottoms/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/women/activewear/"
                },
                {
                  swim:
                    "https://shop.guess.com/en/catalog/browse/women/swimwear/view-all/"
                },
                {
                  lingerie:
                    "https://shop.guess.com/en/catalog/browse/women/lingerie/view-all/"
                }
              ]
            }
          ]
        },
        {
          ca: [
            {
              men: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/men/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/men/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/men/view-all/"
                },
                {
                  tankAndTshirt:
                    "https://shop.guess.com/en/catalog/browse/men/tanks-t-shirts/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/men/jackets-outerwear/view-all/"
                },
                {
                  shirts:
                    "https://shop.guess.com/en/catalog/browse/men/shirts/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/men/sweaters/"
                },
                {
                  pantsAndShorts:
                    "https://shop.guess.com/en/catalog/browse/men/pants-shorts/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/men/activewear/"
                },
                {
                  underwear:
                    "https://shop.guess.com/en/catalog/browse/men/underwear/"
                },
                { swim: "https://shop.guess.com/en/catalog/browse/men/swim/" }
              ]
            },
            {
              women: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/men/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/men/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/men/view-all/"
                },
                {
                  tankAndTshirt:
                    "https://shop.guess.com/en/catalog/browse/men/tanks-t-shirts/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/men/jackets-outerwear/view-all/"
                },
                {
                  shirts:
                    "https://shop.guess.com/en/catalog/browse/men/shirts/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/men/sweaters/"
                },
                {
                  pantsAndShorts:
                    "https://shop.guess.com/en/catalog/browse/men/pants-shorts/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/men/activewear/"
                },
                {
                  underwear:
                    "https://shop.guess.com/en/catalog/browse/men/underwear/"
                },
                { swim: "https://shop.guess.com/en/catalog/browse/men/swim/" }
              ]
            }
          ]
        }
      ]
    },
    {
      name: "Marciano",
      countries: [
        {
          us: [
            {
              men: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/men/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/men/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/men/view-all/"
                },
                {
                  tankAndTshirt:
                    "https://shop.guess.com/en/catalog/browse/men/tanks-t-shirts/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/men/jackets-outerwear/view-all/"
                },
                {
                  shirts:
                    "https://shop.guess.com/en/catalog/browse/men/shirts/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/men/sweaters/"
                },
                {
                  pantsAndShorts:
                    "https://shop.guess.com/en/catalog/browse/men/pants-shorts/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/men/activewear/"
                },
                {
                  underwear:
                    "https://shop.guess.com/en/catalog/browse/men/underwear/"
                },
                { swim: "https://shop.guess.com/en/catalog/browse/men/swim/" }
              ]
            },
            {
              women: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/women/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/women/view-all/"
                },
                {
                  dresses:
                    "https://shop.guess.com/en/catalog/browse/women/dresses/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/women/view-all/"
                },
                {
                  tops:
                    "https://shop.guess.com/en/catalog/browse/women/tops/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/women/jackets-and-outerwear/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/women/sweaters/"
                },
                {
                  bottoms:
                    "https://shop.guess.com/en/catalog/browse/women/bottoms/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/women/activewear/"
                },
                {
                  swim:
                    "https://shop.guess.com/en/catalog/browse/women/swimwear/view-all/"
                },
                {
                  lingerie:
                    "https://shop.guess.com/en/catalog/browse/women/lingerie/view-all/"
                }
              ]
            }
          ]
        },
        {
          ca: [
            {
              men: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/men/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/men/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/men/view-all/"
                },
                {
                  tankAndTshirt:
                    "https://shop.guess.com/en/catalog/browse/men/tanks-t-shirts/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/men/jackets-outerwear/view-all/"
                },
                {
                  shirts:
                    "https://shop.guess.com/en/catalog/browse/men/shirts/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/men/sweaters/"
                },
                {
                  pantsAndShorts:
                    "https://shop.guess.com/en/catalog/browse/men/pants-shorts/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/men/activewear/"
                },
                {
                  underwear:
                    "https://shop.guess.com/en/catalog/browse/men/underwear/"
                },
                { swim: "https://shop.guess.com/en/catalog/browse/men/swim/" }
              ]
            },
            {
              women: [
                {
                  viewAll:
                    "https://shop.guess.com/en/catalog/browse/men/view-all/"
                },
                {
                  newArrivals:
                    "https://shop.guess.com/en/catalog/browse/new-arrivals/men/view-all/"
                },
                {
                  denim:
                    "https://shop.guess.com/en/catalog/browse/denim/men/view-all/"
                },
                {
                  tankAndTshirt:
                    "https://shop.guess.com/en/catalog/browse/men/tanks-t-shirts/view-all/"
                },
                {
                  jackets:
                    "https://shop.guess.com/en/catalog/browse/men/jackets-outerwear/view-all/"
                },
                {
                  shirts:
                    "https://shop.guess.com/en/catalog/browse/men/shirts/view-all/"
                },
                {
                  sweaters:
                    "https://shop.guess.com/en/catalog/browse/men/sweaters/"
                },
                {
                  pantsAndShorts:
                    "https://shop.guess.com/en/catalog/browse/men/pants-shorts/view-all/"
                },
                {
                  activewear:
                    "https://shop.guess.com/en/catalog/browse/men/activewear/"
                },
                {
                  underwear:
                    "https://shop.guess.com/en/catalog/browse/men/underwear/"
                },
                { swim: "https://shop.guess.com/en/catalog/browse/men/swim/" }
              ]
            }
          ]
        }
      ]
    }
  ];
}
